#!/usr/bin/env bash
# scripts/build.sh — bundle public/* assets into src/worker.js as build/worker.js
#
# Static assets (HTML, manifest, service worker, PWA icons) are base64-encoded
# and prepended as `const FOO_B64 = "..."` declarations. The Worker decodes
# them at cold-start with atob() and serves them with the right MIME types.

set -euo pipefail

cd "$(dirname "$0")/.."

mkdir -p build

if ! command -v base64 >/dev/null; then
  echo "base64 not found — install coreutils" >&2
  exit 1
fi

# Cross-platform base64-without-line-wrapping helper.
b64() {
  local f="$1"
  if base64 --help 2>&1 | grep -q -- '-w'; then
    base64 -w 0 "$f"
  else
    base64 -b 0 "$f" 2>/dev/null || base64 < "$f" | tr -d '\n'
  fi
}

HTML_B64=$(b64 public/index.html)
MANIFEST_B64=$(b64 public/manifest.json)
SW_B64=$(b64 public/sw.js)
ICON_192_B64=$(b64 public/icon-192.png)
ICON_512_B64=$(b64 public/icon-512.png)
ICON_MASK_B64=$(b64 public/icon-maskable-512.png)

{
  echo "// Auto-generated by scripts/build.sh — do not edit directly."
  echo "// Source: src/worker.js + public/*"
  echo "const INDEX_HTML_B64 = \"$HTML_B64\";"
  echo "const MANIFEST_B64 = \"$MANIFEST_B64\";"
  echo "const SW_B64 = \"$SW_B64\";"
  echo "const ICON_192_B64 = \"$ICON_192_B64\";"
  echo "const ICON_512_B64 = \"$ICON_512_B64\";"
  echo "const ICON_MASK_B64 = \"$ICON_MASK_B64\";"
  echo ""
  cat src/worker.js
} > build/worker.js

echo "Bundled $(wc -c < build/worker.js) bytes → build/worker.js"
